# Generated by Django 6.0.3 on 2026-04-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('priorite', models.CharField(choices=[('info', 'Information'), ('important', 'Important'), ('urgent', 'Urgent')], default='info', max_length=20, verbose_name='Priorité')),
                ('destinataires_role', models.CharField(blank=True, default='', help_text='Laisser vide pour tous', max_length=20, verbose_name='Rôle destinataire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('membres', models.ManyToManyField(blank=True, related_name='associations_membre', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du cours')),
                ('formation', models.CharField(max_length=100, verbose_name='Formation')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=10, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('salle', models.CharField(max_length=50, verbose_name='Salle')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_enseignes', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.association', verbose_name='Association')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_organises', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('present', models.BooleanField(default=False, verbose_name='Présent')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to='campus.cours', verbose_name='Cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargements', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Émargement',
                'verbose_name_plural': 'Émargements',
                'ordering': ['-date'],
                'unique_together': {('cours', 'etudiant', 'date')},
            },
        ),
    ]
