# Generated by Django 6.0.3 on 2026-03-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConnaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('mots_cles', models.TextField(help_text='Mots-clés séparés par des points-virgules (;)', verbose_name='Mots-clés')),
                ('categorie', models.CharField(choices=[('Scolarité', 'Scolarité'), ('Vie étudiante', 'Vie étudiante'), ('Campus', 'Campus'), ('Stages', 'Stages'), ('Bourses', 'Bourses'), ('Numérique', 'Numérique')], max_length=50, verbose_name='Catégorie')),
                ('lien_document', models.URLField(blank=True, default='', verbose_name='Lien document')),
            ],
            options={
                'verbose_name': 'Question de la base',
                'verbose_name_plural': 'Base de connaissances',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('session_id', models.CharField(default='', max_length=100, verbose_name='Session')),
                ('question_posee', models.TextField(verbose_name='Question posée')),
                ('reponse_fournie', models.TextField(verbose_name='Réponse fournie')),
                ('match_trouve', models.BooleanField(default=False, verbose_name='Match trouvé')),
                ('satisfaction', models.CharField(blank=True, choices=[('', 'Non évalué'), ('Utile', 'Utile'), ('Pas utile', 'Pas utile')], default='', max_length=20, verbose_name='Satisfaction')),
                ('question_matchee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.baseconnaissance', verbose_name='Question matchée')),
            ],
            options={
                'verbose_name': 'Log chatbot',
                'verbose_name_plural': 'Logs chatbot',
                'ordering': ['-date_heure'],
            },
        ),
    ]
